In [0]:
import numpy as np

In [0]:
sample = ['the cat sat on the mat.', 'the rat sat on the cat.']

data = sample

dict = {}
for i in range(len(data)):
  for word in data[i].split():
    if word not in dict:
      dict[word] = len(dict) + 1
      
print (dict)

{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat.': 5, 'rat': 6, 'cat.': 7}


In [0]:
import numpy as np

samples = ['The cat sat on the mat.', 'The dog ate my homework.']      

token_index = {}                                                       
for sample in samples:
    for word in sample.split():                                        
        if word not in token_index:
            token_index[word] = len(token_index) + 1                   

max_length = 10                                                        

print (token_index)

results = np.zeros(shape=(len(samples),
                          max_length,
                          max(token_index.values()) + 1))              
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.
        
print (results)

{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework.': 10}
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [0]:
x = {'a', 'b'}
print (x['a'])
x = ['a', 'b']
print (x[0])
x = ('a', 'b')
print (x[0])

TypeError: ignored

In [0]:
import numpy as np

In [0]:
samples = ['the cat sat on the mat.', 'the rat sat on the cat.']

In [0]:
import re
token_index = {}
max_len = 0
for sample in samples:
  sample = sample.split()
  if max_len < len(sample):
    max_len = len(sample)
  for word in sample:
    word = re.split('\s|(?<!\d)[,.]|[,.](?!\d)', word)[0]
    if word not in token_index:
      token_index[word] = len(token_index) + 1

res = np.zeros((max_len, len(token_index)+1))

for sample in samples:
  resi = np.zeros((max_len, len(token_index)+1))
  x = 0
  for word in sample.split():
    word = re.split('\s|(?<!\d)[,.]|[,.](?!\d)', word)[0]
    resi[x,token_index.get(word)] = 1
    x+=1
  res = np.dstack([res, resi])
res = res[:,:,1:]

In [2]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words = 1000)
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
word_index = tokenizer.word_index

print (sequences)
print (one_hot_results.shape)
print (word_index)

NameError: ignored

In [0]:
from keras. datasets import imdb
from keras import preprocessing

In [0]:
max_feat = 10000
maxlen = 100

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_feat)

x_train = preprocessing.sequence.pad_sequences(x_train, maxlen = maxlen)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen = maxlen)

In [12]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

model = Sequential()
model.add(Embedding(10000, 12, input_length=maxlen))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 12)           120000    
_________________________________________________________________
flatten_3 (Flatten)          (None, 1200)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1201      
Total params: 121,201
Trainable params: 121,201
Non-trainable params: 0
_________________________________________________________________
Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 2s 121us/step - loss: 0.5801 - acc: 0.7144 - val_loss: 0.4147 - val_acc: 0.8242
Epoch 2/10
20000/20000 [==============================] - 2s 96us/step - loss: 0.3346 - acc: 0.8638 - val_loss: 0.3374 - val_acc: 0.8506
Epoch 3/10
20000/20000 [==============================] - 2s 96us/step - los